[theme]
# Primary accent color for interactive elements.
primaryColor = "#89CFFD"

# Background color for the main content area.
backgroundColor = "#002E94"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FFFFFF"

# Color used for almost all text.
textColor = "#EEEEEE"


