[theme]
# Primary accent color for interactive elements.
primaryColor = "#000000"

# Background color for the main content area.
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#000000"

# Color used for almost all text.
textColor = "#EEEEEE"


